upstream django_app {
    server web:8000;
}

upstream fastapi_app {
    server ai_service:8001;
}

server {
    listen 80;
    server_name localhost;

    client_max_body_size 25M;

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }

    location /fastapi/ {
        proxy_pass http://fastapi_app/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://django_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
