# Generated by Django 5.0.14 on 2026-08-03 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Learning Session', max_length=200)),
                ('subject', models.CharField(choices=[('Math', 'Mathematics 🔢'), ('Science', 'Science 🔬'), ('English', 'English & Reading 📖'), ('History', 'World History 🏛️'), ('Geography', 'Geography & Earth 🌍'), ('General Knowledge', 'General Knowledge 💡'), ('Coding', 'Computer Coding 💻'), ('Reasoning', 'Logic & Reasoning 🧠')], default='General Knowledge', max_length=50)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Student'), ('model', 'AI Tutor')], max_length=20)),
                ('content', models.TextField()),
                ('token_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tutor.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
