# Generated by Django 5.0.14 on 2026-08-03 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('push_to_talk', 'Push to Talk'), ('hold_to_talk', 'Hold to Talk'), ('continuous', 'Continuous Conversation')], default='push_to_talk', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('total_duration_seconds', models.IntegerField(default=0)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to='tutor.chatsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en-US', 'English (US)'), ('hi-IN', 'Hindi (भारत)'), ('en-IN', 'Hinglish / Indian English')], default='en-US', max_length=20)),
                ('voice_gender', models.CharField(choices=[('Female', 'Female (Friendly Teacher)'), ('Male', 'Male (Encouraging Mentor)')], default='Female', max_length=20)),
                ('speaking_rate', models.FloatField(default=1.0)),
                ('pitch', models.FloatField(default=1.0)),
                ('auto_listen', models.BooleanField(default=True)),
                ('auto_read', models.BooleanField(default=True)),
                ('wake_mode', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoiceTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('student', 'Student Spoken'), ('ai_tutor', 'AI Teacher Spoken')], max_length=20)),
                ('transcript_text', models.TextField()),
                ('language', models.CharField(default='en-US', max_length=20)),
                ('confidence_score', models.FloatField(default=0.95)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voice_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='tutor.voicesession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AudioMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_format', models.CharField(default='audio/webm', max_length=30)),
                ('sample_rate', models.IntegerField(default=44100)),
                ('duration_ms', models.IntegerField(default=0)),
                ('file_size_bytes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audio_metadata', to='tutor.voicetranscript')),
            ],
        ),
    ]
