# Generated by Django 5.0.14 on 2026-08-03 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_voicesession_voicesettings_voicetranscript_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MathSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detected_expression', models.TextField()),
                ('status', models.CharField(choices=[('solving', 'Solving'), ('solved', 'Solved'), ('hint_given', 'Hint Provided')], default='solving', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MathSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_answer', models.TextField()),
                ('step_by_step_explanation', models.TextField()),
                ('hint_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('math_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='tutor.mathsession')),
            ],
        ),
        migrations.CreateModel(
            name='Whiteboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Math Workspace', max_length=200)),
                ('mode', models.CharField(choices=[('Drawing', 'Freehand Drawing 🎨'), ('Math Practice', 'Math Practice 🔢'), ('Geometry', 'Geometry 📐'), ('Mind Map', 'Mind Map 🧠'), ('Science Diagram', 'Science Diagram 🔬'), ('Flowchart', 'Flowchart 🔀')], default='Math Practice', max_length=50)),
                ('canvas_json', models.TextField(default='{}')),
                ('thumbnail_url', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whiteboards', to='tutor.chatsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whiteboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='mathsession',
            name='whiteboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='math_sessions', to='tutor.whiteboard'),
        ),
        migrations.CreateModel(
            name='DrawingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_json', models.TextField()),
                ('action_type', models.CharField(default='draw', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tutor.whiteboard')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AutoSaveSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_data', models.TextField()),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autosaves', to='tutor.whiteboard')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.CreateModel(
            name='WhiteboardElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('element_type', models.CharField(max_length=50)),
                ('element_data', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('whiteboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='tutor.whiteboard')),
            ],
        ),
    ]
