# Generated by Django 5.0.14 on 2026-08-03 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_mathsession_mathsolution_whiteboard_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('subject', models.CharField(default='General Knowledge', max_length=50)),
                ('visualization_type', models.CharField(choices=[('Flowchart', 'Interactive Flowchart 🔀'), ('Mind Map', 'Mind Map Concept 🧠'), ('Timeline', 'Historical Timeline ⏳'), ('Chart', 'Data Chart / Graph 📊'), ('Cycle Diagram', 'Cycle Diagram 🔄'), ('Interactive Cards', 'Visual Step Cards 🎴')], default='Flowchart', max_length=50)),
                ('explanation_text', models.TextField()),
                ('analogy_text', models.TextField(blank=True)),
                ('diagram_data', models.TextField()),
                ('quiz_data', models.TextField(default='[]')),
                ('summary_text', models.TextField(blank=True)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visual_lessons', to='tutor.chatsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visual_lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_history', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='tutor.visuallesson')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonDiagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagram_type', models.CharField(default='flowchart', max_length=50)),
                ('code_definition', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagrams', to='tutor.visuallesson')),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmarked_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_lessons', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='tutor.visuallesson')),
            ],
            options={
                'ordering': ['-bookmarked_at'],
            },
        ),
        migrations.CreateModel(
            name='AnimationAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animation_type', models.CharField(default='lottie', max_length=50)),
                ('asset_url', models.TextField(blank=True)),
                ('animation_config', models.TextField(default='{}')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animations', to='tutor.visuallesson')),
            ],
        ),
    ]
