# Generated by Django 5.0.14 on 2026-08-03 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_visuallesson_lessonhistory_lessondiagram_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Scanned Homework', max_length=200)),
                ('subject', models.CharField(default='General Knowledge', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('Easy', 'Easy 🟢'), ('Medium', 'Medium 🟡'), ('Hard', 'Hard 🔴'), ('Challenge', 'Challenge 🏆')], default='Medium', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Scan'), ('processing', 'OCR Processing'), ('analyzed', 'Analyzed'), ('completed', 'Completed')], default='pending', max_length=30)),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='tutor.chatsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=1)),
                ('question_text', models.TextField()),
                ('subject_tag', models.CharField(default='General Knowledge', max_length=50)),
                ('difficulty', models.CharField(default='Medium', max_length=30)),
                ('step_by_step_solution', models.TextField()),
                ('hint_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tutor.homework')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_overview', models.TextField()),
                ('key_concepts_found', models.TextField(default='[]')),
                ('student_errors_found', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='tutor.homework')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_submission_text', models.TextField()),
                ('ai_feedback', models.TextField()),
                ('score_achieved', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tutor.homework')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_obj', models.FileField(upload_to='homework_uploads/')),
                ('file_type', models.CharField(default='image', max_length=30)),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='tutor.homework')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_history', to='tutor.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField()),
                ('cleaned_text', models.TextField()),
                ('confidence_score', models.FloatField(default=0.95)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to='tutor.homework')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(default='Medium', max_length=30)),
                ('question_text', models.TextField()),
                ('options_json', models.TextField(default='[]')),
                ('correct_index', models.IntegerField(default=0)),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_questions', to='tutor.detectedquestion')),
            ],
        ),
    ]
