# Generated by Django 5.0.14 on 2026-08-03 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_homework_detectedquestion_homeworkanalysis_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(default='English', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner 🌱'), ('Intermediate', 'Intermediate 🌿'), ('Advanced', 'Advanced 🌳')], default='Beginner', max_length=30)),
                ('content_text', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('audio_url', models.TextField(blank=True)),
                ('language', models.CharField(default='en-US', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_passages_read', models.IntegerField(default=0)),
                ('total_words_read', models.IntegerField(default=0)),
                ('average_accuracy', models.FloatField(default=0.0)),
                ('average_wpm', models.FloatField(default=0.0)),
                ('total_reading_xp', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_focus_words', models.TextField(default='[]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.readingpassage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('guided', 'Guided Reading 📖'), ('independent', 'Independent Reading 🎤'), ('echo', 'Echo Reading 🔁'), ('challenge', 'Challenge Reading ⏱️')], default='independent', max_length=30)),
                ('language', models.CharField(default='en-US', max_length=20)),
                ('status', models.CharField(default='reading', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='tutor.chatsession')),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tutor.readingpassage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_format', models.CharField(default='audio/webm', max_length=30)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('spoken_transcript', models.TextField()),
                ('words_per_minute', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recording', to='tutor.readingsession')),
            ],
        ),
        migrations.CreateModel(
            name='PronunciationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_score', models.FloatField(default=0.0)),
                ('fluency_score', models.FloatField(default=0.0)),
                ('pacing_score', models.FloatField(default=0.0)),
                ('overall_score', models.FloatField(default=0.0)),
                ('skipped_words_count', models.IntegerField(default=0)),
                ('repeated_words_count', models.IntegerField(default=0)),
                ('mispronounced_words_count', models.IntegerField(default=0)),
                ('gemini_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='tutor.readingsession')),
            ],
        ),
        migrations.CreateModel(
            name='WordAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_word', models.CharField(max_length=100)),
                ('spoken_word', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('correct', 'Correct 🟩'), ('mispronounced', 'Mispronounced 🟥'), ('skipped', 'Skipped 🟨'), ('repeated', 'Repeated 🟧')], default='correct', max_length=30)),
                ('phoneme_hint', models.CharField(blank=True, max_length=100)),
                ('score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='tutor.pronunciationscore')),
            ],
        ),
    ]
