# Generated by Django 5.0.14 on 2026-08-03 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_readingpassage_readingprogress_readingrecommendation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('School', 'School & Teacher 🏫'), ('Restaurant', 'Ordering at Restaurant 🍕'), ('Doctor', 'Doctor & Health 🩺'), ('Airport', 'Airport & Travel ✈️'), ('Science', 'Science Lab Experiment 🔬'), ('Debate', 'Student Debate 🗣️'), ('Storytelling', 'Interactive Storytelling 📖'), ('Shopping', 'Shopping Mall 🛒')], default='School', max_length=50)),
                ('description', models.TextField()),
                ('ai_role_name', models.CharField(default='Sparky AI', max_length=100)),
                ('initial_greeting', models.TextField()),
                ('system_prompt', models.TextField()),
                ('icon_class', models.CharField(default='bi-chat-dots-fill', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('xp_reward', models.IntegerField(default=50)),
                ('is_daily', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grammar_score', models.FloatField(default=0.0)),
                ('vocabulary_score', models.FloatField(default=0.0)),
                ('fluency_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('overall_speaking_score', models.FloatField(default=0.0)),
                ('summary_report', models.TextField()),
                ('xp_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=100)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GrammarCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_sentence', models.TextField()),
                ('corrected_sentence', models.TextField()),
                ('explanation_rule', models.TextField()),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grammar_corrections', to='tutor.speakingfeedback')),
            ],
        ),
        migrations.CreateModel(
            name='SpeakingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active Conversation'), ('completed', 'Completed & Evaluated')], default='active', max_length=30)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaking_sessions', to='tutor.chatsession')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tutor.conversationscenario')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaking_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='speakingfeedback',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tutor.speakingsession'),
        ),
        migrations.CreateModel(
            name='ConversationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('student', 'Student Spoken'), ('ai_coach', 'AI Speaking Coach')], max_length=20)),
                ('text_content', models.TextField()),
                ('audio_url', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='tutor.speakingsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('better_synonym', models.CharField(max_length=100)),
                ('times_used', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
