# Generated by Django 5.0.14 on 2026-08-03 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_conversationscenario_speakingchallenge_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='avatar', max_length=50)),
                ('icon_class', models.CharField(default='bi-robot', max_length=100)),
                ('cost_coins', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(default='General Knowledge', max_length=50)),
                ('game_type', models.CharField(choices=[('match_pair', 'Match the Pair 🃏'), ('memory_cards', 'Memory Flip Cards 🧠'), ('interactive_quiz', 'Interactive Quiz ⚡'), ('drag_drop', 'Drag & Drop Bins 🎯'), ('sorting', 'Concept Sorting 🔀')], default='match_pair', max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy 🟢'), ('Medium', 'Medium 🟡'), ('Hard', 'Hard 🔴'), ('Challenge', 'Challenge 🏆'), ('Master', 'Master 👑')], default='Easy', max_length=30)),
                ('config_json', models.TextField(default='{}')),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='tutor.chatsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GameQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('distractors_json', models.TextField(default='[]')),
                ('hint', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tutor.game')),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('max_score', models.IntegerField(default=100)),
                ('time_spent_seconds', models.IntegerField(default=0)),
                ('status', models.CharField(default='playing', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tutor.game')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_earned', models.IntegerField(default=0)),
                ('coins_earned', models.IntegerField(default=0)),
                ('stars_earned', models.IntegerField(default=3)),
                ('accuracy_percentage', models.FloatField(default=0.0)),
                ('feedback_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='tutor.gamesession')),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_xp', models.IntegerField(default=0)),
                ('rank_position', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-weekly_xp'],
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('target_count', models.IntegerField(default=1)),
                ('current_count', models.IntegerField(default=0)),
                ('xp_reward', models.IntegerField(default=50)),
                ('coins_reward', models.IntegerField(default=25)),
                ('is_completed', models.BooleanField(default=False)),
                ('period', models.CharField(choices=[('daily', 'Daily Mission ☀️'), ('weekly', 'Weekly Quest 📅'), ('monthly', 'Monthly Milestone 🏆')], default='daily', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_balance', models.IntegerField(default=100)),
                ('total_xp', models.IntegerField(default=0)),
                ('daily_streak', models.IntegerField(default=1)),
                ('unlocked_items_json', models.TextField(default='["sparky_robot"]')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reward_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
