# Generated by Django 5.0.14 on 2026-08-03 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_avatar_game_gamequestion_gamesession_gameresult_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('learning_speed_score', models.FloatField(default=85.0)),
                ('retention_trend_score', models.FloatField(default=88.0)),
                ('weak_topics_json', models.TextField(default='["Fractions", "Past Tense"]')),
                ('strong_topics_json', models.TextField(default='["Addition", "Vocabulary"]')),
                ('ai_recommendation_text', models.TextField(default='Practice Fractions for 10 minutes tomorrow to build confidence!')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('study_time_minutes', models.IntegerField(default=0)),
                ('chats_count', models.IntegerField(default=0)),
                ('voice_minutes', models.IntegerField(default=0)),
                ('whiteboards_solved', models.IntegerField(default=0)),
                ('visual_lessons_viewed', models.IntegerField(default=0)),
                ('homeworks_completed', models.IntegerField(default=0)),
                ('reading_passages_read', models.IntegerField(default=0)),
                ('speaking_sessions_done', models.IntegerField(default=0)),
                ('games_played', models.IntegerField(default=0)),
                ('xp_gained', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DailyStudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('plan_json', models.TextField(default='{"Math":20, "Science":15, "Reading":15, "Speaking":10, "Homework":10, "Games":10}')),
                ('total_target_minutes', models.IntegerField(default=80)),
                ('total_completed_minutes', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('hw_completed', 'Homework Completed 📝'), ('goal_achieved', 'Daily Goal Achieved 🎯'), ('badge_unlocked', 'Badge Unlocked 🏆'), ('inactivity', 'Study Reminder ⏰'), ('weak_perf', 'Needs Practice Alert 💡'), ('login_alert', 'New Login Alert 🔒')], default='goal_achieved', max_length=50)),
                ('channel', models.CharField(choices=[('in_app', 'In-App Notification'), ('sms', 'SMS Message'), ('whatsapp', 'WhatsApp Message'), ('email', 'Email Message')], default='in_app', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_status', models.CharField(default='sent', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_sms', models.BooleanField(default=True)),
                ('enable_whatsapp', models.BooleanField(default=True)),
                ('enable_email', models.BooleanField(default=True)),
                ('enable_in_app', models.BooleanField(default=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentChildRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_parents', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='Grade 4 Alpha', max_length=100)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_students', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('teacher', 'student')},
            },
        ),
    ]
