# Generated by Django 5.0.14 on 2026-08-03 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_analyticssnapshot_dailyprogress_dailystudyplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeGraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Math', max_length=50)),
                ('tree_json', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdaptivePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curriculum_json', models.TextField(default='[]')),
                ('difficulty_level', models.CharField(default='Adaptive', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adaptive_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('target_date', models.DateField()),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength_summary', models.TextField()),
                ('weakness_summary', models.TextField()),
                ('predicted_milestone', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_insight', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LearningProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_level', models.CharField(default='Beginner', max_length=30)),
                ('speaking_level', models.CharField(default='Intermediate', max_length=30)),
                ('preferred_learning_style', models.CharField(default='Visual Learner', max_length=50)),
                ('preferred_teaching_style', models.CharField(default='Socratic & Encouraging', max_length=50)),
                ('weak_concepts_json', models.TextField(default='["Fractions", "Past Tense"]')),
                ('strong_concepts_json', models.TextField(default='["Addition", "Vocabulary"]')),
                ('common_mistakes_json', models.TextField(default='[]')),
                ('avg_study_duration_mins', models.FloatField(default=45.0)),
                ('confidence_score', models.FloatField(default=85.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role', models.CharField(choices=[('student', 'Student Action'), ('parent', 'Parent Tip'), ('teacher', 'Teacher Insight')], default='student', max_length=20)),
                ('action_text', models.TextField()),
                ('category', models.CharField(default='Practice', max_length=50)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RevisionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('interval_days', models.IntegerField(default=1)),
                ('scheduled_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Math', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('parent_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tutor.skillnode')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_study_hour', models.IntegerField(default=16)),
                ('most_active_day', models.CharField(default='Wednesday', max_length=20)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_pattern', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SkillProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started ⚪'), ('learning', 'Learning 🟡'), ('practicing', 'Practicing 🔵'), ('mastered', 'Mastered 🟢'), ('revision_needed', 'Revision Needed 🔴')], default='not_started', max_length=30)),
                ('mastery_percentage', models.FloatField(default=0.0)),
                ('last_practiced', models.DateTimeField(auto_now=True)),
                ('skill_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='tutor.skillnode')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'skill_node')},
            },
        ),
    ]
