# Generated by Django 5.0.14 on 2026-08-03 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_knowledgegraph_adaptiveplan_learninggoal_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherStudent',
        ),
    ]
