# Generated by Django 5.0.14 on 2026-08-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_studentprofile_parent_name_user_city_user_country_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='failedloginattempt',
            name='identifier',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Student', 'Student'), ('Parent', 'Parent'), ('Admin', 'Admin')], default='Student', max_length=20, verbose_name='User Role'),
        ),
        migrations.DeleteModel(
            name='TeacherProfile',
        ),
    ]
